### ISSUE TITLE
Ciceksepeti order retrieve

### ISSUE THREAD

**Issue by developkariyer** [developkariyer/iwapim#30]
Does pim try to retrieve all orders every night from Ciceksepeti? Does it have a filter functionality to retrieve only new orders.

p.s. Orders to be retrieved are determined by checking last update times (not creation or order times). Check for the latest update time in database, ask Ciceksepeti to send orders updated at or after that given last update time.

**Comment by enesbt** [comment]
Ciceksepeti orders opened for testing, not included in the order table, will be added

**Comment by enesbt** [comment]
ciceksepeti orders are ready to be added to the orders table every night according to the last update date.
